### ISSUE TITLE
Bone Meal behavior and crash

### ISSUE THREAD

**Issue by cryxli** [MrFantiVideo/MineGate#21] opened 2022-02-18 10:21 UTC
### Observation 

When Bone Meal-ing vanilla Grass Blocks not only flowers are generated, but trees, too. Especially Azalea appear all the time. But I already have seen Dark Oak and Spruce.

Basically, with MineGate you can turn your flower farm into a tree farm. But its a little bit of a headache. :-D

I would expect that Bone Meal only produces flowers, tall grass, etc. but not trees.

### Setup

- [minegate-moreblocks-1.1.8.jar](https://www.curseforge.com/minecraft/mc-mods/minegate-moreblocks/files/3549515)
- [fabric-api-0.46.4+1.18.jar](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3634318)
- Minecraft 1.18.1

### Guess Work

It most likely relates to issue #10. The SlabGrassBlock mixin seems to trigger with vanilla Grass Blocks, too. And then delegates flower growing to chunk managers. They use the world gen logic to generate everything, not just flowers.

This guess is supported by the [crash-2022-02-18_11.05.18-server.txt](https://github.com/MrFantiVideo/MineGate/files/8096135/crash-2022-02-18_11.05.18-server.txt) I see occasionally. I cannot reproduce it reliably. But perhaps it helps. - It comes from a flower farm, that only uses vanilla Grass Blocks that are moved back and forth with pistons. The classic.

### Suggestion

Disable the SlabGrassBlock.growAll()  with a config property until the behavior is understood and eventually fixed.

I really like the variety MineGate adds to Fabric. Great work!

**Comment by Laifsyn** [comment] 2022-03-28 14:40
Hey, a follow up. Apparently it also grows hay bales ^^;

**Comment by MrFantiVideo** [comment] 2022-05-15 13:06
Fixed in the new version. ([MoreBlocks 1.2.0](https://github.com/MrFantiVideo/MineGate/releases/tag/1.2.0))
I would like to have your confirmation, to be sure that I have found the cause of the problem.

**Comment by himbeerschaf** [comment] 2022-05-20 09:55
Hello! We were having the same issue with the bonemeal and I'm happy to see you fixed it :) 
We're playing on a server on v1.18.1, is there a chance to somehow get the fix for the older version, too?

I'm very sorry if this is a stupid question to ask, I don't know anything about coding :/ All I know is that we can't update since most of the mods we use are still on 1.18.1 (which is a bummer).

Thank you for your time :)

**Comment by MrFantiVideo** [comment] 2022-05-20 16:57
> Hello! We were having the same issue with the bonemeal and I'm happy to see you fixed it :) We're playing on a server on v1.18.1, is there a chance to somehow get the fix for the older version, too?
> 
> I'm very sorry if this is a stupid question to ask, I don't know anything about coding :/ All I know is that we can't update since most of the mods we use are still on 1.18.1 (which is a bummer).
> 
> Thank you for your time :)

I don't think to update the old versions, I will eventually see to do it as soon as I have fixed some bugs of the new version.

**Comment by himbeerschaf** [comment] 2022-05-20 19:25
> 

Understandable. Thank you for your reply!  :)

**Closed** 2022-05-22 07:14 UTC
Labels: Resolved, Bug
